#设置端口
server:
  port: 5001

spring:
  #对外暴露的名字
  application:
    name: provider-hystrix-8004
  rabbitmq:
    host: 127.0.0.1
    port: 15672
    username: guest
    password: guest
    listener:
      simple:
        #并发消费者的初始值
        concurrency: 10
        #并发消费者的最大值
        max-concurrency: 20
        #每个消费者每次监听时可拉取处理的消息数量
        prefetch: 5
