#设置端口
server:
  port: 5001

spring:
  rabbitmq:
    #IP地址
    host: 127.0.0.1
    #端口
    port: 5672
    #用户名
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 20
        #消费者每次处理一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试，默认false
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数，默认3次
        max-attempts: 3
        #重试最大间隔时间，默认10000ms
        max-interval: 10000ms
        #重试地间隔乘数。如2.0,第一次等10秒，第二次等20s，第三次等40s。
        multiplier: 1