#设置端口
server:
  port: 3344

spring:
  #对外暴露的名字
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #git仓库地址
          uri: https://gitee.com/yu-lin/springcloud02-config.git
          #搜索仓库中的目录
          search-paths:
            - config
      #读取的分支
      label: main

#eureka客户端配置
eureka:
  instance:
    #应用在eureka中的别名名称
    instance-id: cloud-config-center-3344
    #是否显示应用自身的IP地址
    prefer-ip-address: true
  client:
    #要注册进入的eureka的IP地址(多个地址表示注册进入集群)
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#配置回显信息
info:
  author: 李家霖
  build-version: 0.0.1-SNAPSHOT
