#设置端口
server:
  port: 6001

#eureka客户端配置
eureka:
  instance:
    #应用在eureka中的别名名称
    instance-id: zuul.com
    #是否显示应用自身的IP地址
    prefer-ip-address: true
  client:
    #要注册进入的eureka的IP地址(多个地址表示注册进入集群)
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#zuul配置
zuul:
  routes:
    #此子项目访问地址: http://zuul.com:6001/prefix/dept/
    #provider8004是自定义的名字，只作为区分无实际意义
    provider8004.serviceId: provider-hystrix-8004
    #自定义路径，支持通配符
    provider8004.path: /dept/**
  #需要隐藏的服务名，可以使用通配符，配置之后通过这个微服务名访问就失效了
  ignored-services: provider*
  prefix: /prefix

spring:
  #对外暴露的名字
  application:
    name: zuul
