#端口配置
server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，职责是维护实例，不参加检索
    fetch-registry: false
    #设置eureka server的交互地址，即对外暴露的地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/